# -*- coding: utf-8 -*-
"""JSON Refiner Advanced Edition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QvyBAh9FMAqthK1KXmA71GnQwYmdV7N0
"""

!pip install -U transformers
!pip install json5

#use a pipeline as a high-level helper
from transformers import pipeline
pipe = pipeline("text-generation",model="ibm-granite/granite-3.3-2b-instruct"
)
messages=[
    {"role":"user","content":"Who are you?"},
]
pipe(messages)

#Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user","content":"Who are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize = True,
    return_dict = True,
    return_tensors="pt",
).to(model.device)
outputs=model.generate(**inputs,max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

import gradio as gr
import json
import re
import ast
from datetime import datetime
from pathlib import Path
from typing import Dict,List,Any,Tuple,Optional
import json5
from jsonschema import validate,ValidationError,Draft7Validator
from enum import Enum
# ==============================================================================================================================================
# JSON REFINER - ADVANCED VERSION WITH PREMIUM FEATURES (FIXED)
# ==============================================================================================================================================

class CaseStyle(Enum):
    """Case conversion styles"""
    SNAKE_CASE = "snake_case"
    CAMEL_CASE = "camelCase"
    KEBAB_CASE = "kebab-case"
    PASCAL_CASE = "PascalCase"

class JSONRefinerCore:
    """Advanced JSON parsing and refinement engine"""

    def __init__(self):
        self.conversion_log = []
        self.validation_errors = []
        self.transformation_history = []


    @staticmethod
    def to_snake_case(key: str) -> str:
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', key)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

    @staticmethod
    def to_camel_case(key: str) -> str:
        s = JSONRefinerCore.to_snake_case(key).split('_')
        return s[0] + ''.join(word.capitalize() for word in s[1:])

    @staticmethod
    def to_pascal_case(key: str) -> str:
        s = JSONRefinerCore.to_snake_case(key).split('_')
        return ''.join(word.capitalize() for word in s)

    @staticmethod
    def to_kebab_case(key: str) -> str:
        return JSONRefinerCore.to_snake_case(key).replace('_', '-')

    def normalize_key(self, key: str, target_case: CaseStyle) -> str:
        converted_key = key
        if target_case == CaseStyle.SNAKE_CASE:
            converted_key = JSONRefinerCore.to_snake_case(key)
        elif target_case == CaseStyle.CAMEL_CASE:
            converted_key = JSONRefinerCore.to_camel_case(key)
        elif target_case == CaseStyle.KEBAB_CASE:
            converted_key = JSONRefinerCore.to_kebab_case(key)
        elif target_case == CaseStyle.PASCAL_CASE:
            converted_key = JSONRefinerCore.to_pascal_case(key)

        if converted_key != key:
            self.conversion_log.append(f"Key '{key}' converted to '{converted_key}' ({target_case.value})")
        return converted_key

    @staticmethod
    def infer_type(value: str) -> Any:
        """Infer and convert value to correct JSON type"""
        value = value.strip()

        if value.lower() in ['null', 'none', 'nil', 'undefined', 'n/a', 'na']:
            return None

        if value.lower() in ['true', 'yes', 'on', '1']:
            return True
        if value.lower() in ['false', 'no', 'off', '0']:
            return False

        try:
            if '.' not in value:
                return int(value)
            else:
                return float(value)
        except ValueError:
            pass

        if (value.startswith('[') and value.endswith(']')) or \
           (value.startswith('{') and value.endswith('}')):
            try:
                return json5.loads(value)
            except ValueError:
                pass

        return value

    def refine_json(self, text_input: str, case_style: CaseStyle, remove_nulls: bool, flatten: bool) -> Tuple[str, List[str]]:
        """Refine JSON from key-value text"""
        self.conversion_log = []
        self.validation_errors = []
        parsed_data, errors = self.parse_key_value_text(text_input, case_style)

        if remove_nulls:
            parsed_data = self.remove_null_values(parsed_data)
            self.transformation_history.append((datetime.now(), "Removed null values"))

        if flatten:
            parsed_data = self.flatten_json(parsed_data)
            self.transformation_history.append((datetime.now(), "Flattened JSON"))

        output_json = json.dumps(parsed_data, indent=2, ensure_ascii=False)
        return output_json, self.conversion_log + errors

    @staticmethod
    def parse_key_value_text(text: str, case_style: CaseStyle = CaseStyle.SNAKE_CASE) -> Tuple[Dict, List[str]]:
        """Parse key-value text into dictionary"""
        result = {}
        errors = []
        duplicates = []

        lines = text.split('\n')

        for line_num, line in enumerate(lines, 1):
            line = line.strip()

            if not line or line.startswith('#'):
                continue

            if ':' not in line:
                errors.append(f"Line {line_num}: No colon separator found - '{line}'")
                continue

            try:
                key, value = line.split(':', 1)
                key = key.strip()

                if key in result:
                    duplicates.append(f"Line {line_num}: Duplicate key '{key}' found. Using latest value.")

                result[key] = JSONRefinerCore.infer_type(value)
            except Exception as e:
                errors.append(f"Line {line_num}: Error parsing '{line}' - {e}")
        return result, errors + duplicates

    @staticmethod
    def remove_null_values(obj: Any) -> Any:
        """Recursively remove null values from dicts and lists"""
        if isinstance(obj, dict):
            return {k: JSONRefinerCore.remove_null_values(v) for k, v in obj.items() if v is not None}
        elif isinstance(obj, list):
            return [JSONRefinerCore.remove_null_values(elem) for elem in obj if elem is not None]
        return obj

    @staticmethod
    def flatten_json(data: Dict, parent_key: str = '', sep: str = '.') -> Dict:
        """Flatten a nested JSON dictionary"""
        items = []
        for k, v in data.items():
            new_key = parent_key + sep + k if parent_key else k
            if isinstance(v, dict):
                items.extend(JSONRefinerCore.flatten_json(v, new_key, sep=sep).items())
            else:
                items.append((new_key, v))
        return dict(items)

    @staticmethod
    def unflatten_json(data: Dict, sep: str = '.') -> Dict:
        """Unflatten a flattened JSON dictionary"""
        result = {}
        for key, value in data.items():
            parts = key.split(sep)
            d = result
            for part in parts[:-1]:
                if part not in d:
                    d[part] = {}
                d = d[part]
            d[parts[-1]] = value
        return result

    @staticmethod
    def validate_json_schema(data: Dict, schema: Dict) -> Tuple[bool, List[str]]:
        """Validate JSON against schema"""
        errors = []
        try:
            validate(instance=data, schema=schema)
            return True, []
        except ValidationError as e:
            return False, [str(e)]
        except Exception as e:
            return False, [f"Schema validation error: {str(e)}"]

    @staticmethod
    def check_required_fields(data: Dict, required_fields: List[str]) -> Tuple[bool, List[str]]:
        """Check for required fields"""
        errors = []
        missing = []
        for field in required_fields:
            if field not in data:
                missing.append(field)

        if missing:
            return False, [f"Missing required fields: {', '.join(missing)}"]
        return True, []

    def merge_json_objects(self, json_strings: List[str]) -> Tuple[str, str]:
        """Merge multiple JSON strings into one"""
        merged_data = {}
        errors = []
        for i, json_str in enumerate(json_strings):
            if not json_str.strip():
                continue
            try:
                data = json.loads(json_str)
                if not isinstance(data, dict):
                    errors.append(f"Input {i+1} is not a JSON object and cannot be merged.")
                    continue
                merged_data.update(data)
            except json.JSONDecodeError as e:
                errors.append(f"Error parsing JSON input {i+1}: {e}")

        if errors:
            return "", "❌ " + "; ".join(errors)
        else:
            self.transformation_history.append((datetime.now(), f"Merged {len(json_strings)} JSON objects"))
            return json.dumps(merged_data, indent=2, ensure_ascii=False), "✅ JSON objects merged!"

    def get_history(self) -> str:
        """Return the transformation history"""
        if not self.transformation_history:
            return "No transformations performed yet."
        report = "Transformation History:\n"
        for timestamp, action in self.transformation_history:
            report += f"- {timestamp.strftime('%Y-%m-%d %H:%M:%S')} : {action}\n"
        return report

    def clear_history(self):
        """Clear the transformation history"""
        self.transformation_history = []

refiner = JSONRefinerCore()

def process_json(text_input, case_style_str, remove_nulls, flatten, pretty_print):
    case_style = CaseStyle[case_style_str.upper().replace("-", "_")]
    refined_json, logs = refiner.refine_json(text_input, case_style, remove_nulls, flatten)
    status_message = "\n".join([f"* {log}" for log in logs]) if logs else "✅ JSON processed successfully!"
    return refined_json, status_message

def validate_json(json_text, schema_text, required_fields_str):
    errors = []
    try:
        data = json.loads(json_text)
    except json.JSONDecodeError as e:
        return False, [f"Invalid JSON: {e}"]

    is_valid_schema, schema_errors = True, []
    if schema_text.strip():
        try:
            schema = json.loads(schema_text)
            is_valid_schema, schema_errors = refiner.validate_json_schema(data, schema)
        except json.JSONDecodeError as e:
            schema_errors.append(f"Invalid Schema JSON: {e}")

    required_fields = [f.strip() for f in required_fields_str.split(',') if f.strip()]
    is_valid_fields, field_errors = refiner.check_required_fields(data, required_fields)

    all_errors = schema_errors + field_errors
    if not is_valid_schema or not is_valid_fields:
        return "❌ Validation Failed", "\n".join(all_errors) if all_errors else "Unknown validation error."
    return "✅ Validation Successful!", "No validation errors."

def convert_case(json_text: str, target_case: str) -> Tuple[str, str]:
    """Convert JSON keys to different case styles"""
    try:
        data = json.loads(json_text)
        case_enum = CaseStyle[target_case.upper().replace("-", "_")]

        def convert_keys(obj):
            if isinstance(obj, dict):
                return {
                    refiner.normalize_key(k, case_enum): convert_keys(v)
                    for k, v in obj.items()
                }
            elif isinstance(obj, list):
                return [convert_keys(item) for item in obj]
            return obj

        converted = convert_keys(data)
        output = json.dumps(converted, indent=2, ensure_ascii=False)
        refiner.transformation_history.append((datetime.now(), f"Converted to {target_case} case"))
        return output, f"✅ Converted to {target_case}!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def merge_json_func(json1_str, json2_str, json3_str):
    json_list = [json1_str, json2_str, json3_str]
    merged_json, status = refiner.merge_json_objects(json_list)
    return merged_json, status

def flatten_json_func(json_text: str) -> Tuple[str, str]:
    """Flatten JSON structure"""
    try:
        data = json.loads(json_text)
        flattened = refiner.flatten_json(data)
        output = json.dumps(flattened, indent=2, ensure_ascii=False)
        refiner.transformation_history.append((datetime.now(), "Flattened JSON"))
        return output, "✅ JSON flattened!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def unflatten_json_func(json_text: str) -> Tuple[str, str]:
    """Unflatten JSON structure"""
    try:
        data = json.loads(json_text)
        unflattened = refiner.unflatten_json(data)
        output = json.dumps(unflattened, indent=2, ensure_ascii=False)
        refiner.transformation_history.append((datetime.now(), "Unflattened JSON"))
        return output, "✅ JSON unflattened!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def download_history():
    return refiner.get_history()

def clear_history():
    refiner.clear_history()
    return "History cleared."


with gr.Blocks(title="JSON Refiner") as demo:
    gr.Markdown("# 🗄️ JSON Refiner - Advanced Edition")

    with gr.Tabs():
        # ================== TAB 1 : Core Refining ========================
        with gr.TabItem("Core Refining"):
            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("### 📄 Input Format")
                    text_input = gr.Textbox(
                        label="Key-Value Text",
                        lines=12,
                        value="name: John Doe\nage: 28\nis_active: true\nbalance: 1500.50\nemail: john@example.com\ntags: [\"admin\", \"user\"]"
                    )
                    case_style = gr.Radio(
                        ["snake_case", "camelCase", "kebab-case", "PascalCase"],
                        value="snake_case",
                        label="Key Case Style 😊"
                    )

                with gr.Column(scale=2):
                    gr.Markdown("### 🛠️ Refined JSON Output")
                    json_output = gr.Code(
                        language="json",
                        label="Output JSON",
                        lines=15,
                    )
                    status_output = gr.Markdown()

            with gr.Row():
                remove_nulls = gr.Checkbox(label="Remove Nulls", value=False)
                flatten = gr.Checkbox(label="Flatten", value=False)
                pretty_print = gr.Checkbox(label="Pretty Print", value=True)
                refine_btn = gr.Button("✨ Refine JSON", size="lg", variant="primary")

            refine_btn.click(
                process_json,
                inputs=[text_input, case_style, remove_nulls, flatten, pretty_print],
                outputs=[json_output, status_output]
            )

        # ============== TAB 2: Validation ==============
        with gr.TabItem("☑️ Validation"):
            gr.Markdown("### 🔍 Validate JSON Structure")

            with gr.Row():
                with gr.Column(scale=1):
                    json_to_validate = gr.Code(
                        language="json",
                        label="JSON to Validate",
                        lines=10,
                        value='{"name": "John", "age": 28,"email":"john@example.com"}'
                    )
                    required_fields_input = gr.Textbox(
                        label="Required Fields (comma-separated)",
                        value="name, age, email"
                    )
                    validate_btn = gr.Button("✅ Validate", size="lg", variant="primary")

                with gr.Column(scale=1):
                    schema_input = gr.Code(
                        language="json",
                        label="JSON Schema (optional)",
                        lines=10,
                        value='{"type": "object", "properties": {"name": {"type": "string"}, "age": {"type": "integer"}}, "required": ["name"]}'
                    )
                    validation_status = gr.Markdown()
                    validation_errors_output = gr.Textbox(label="Validation Details", lines=5)

            validate_btn.click(
                validate_json,
                inputs=[json_to_validate, schema_input, required_fields_input],
                outputs=[validation_status, validation_errors_output]
            )

        # ==== TAB 3: Case Conversion ============
        with gr.TabItem("🐼 Case Conversion"):
            gr.Markdown("### 🐙 Convert JSON Key Cases")

            with gr.Row():
                with gr.Column(scale=1):
                    json_for_case = gr.Code(
                        language="json",
                        label="Input JSON",
                        lines=10,
                        value='{"firstName": "John", "lastName": "Doe"}'
                    )

                    target_case = gr.Radio(
                        ["snake_case", "camel_case", "kebab-case", "pascal_case"],
                        value="camelCase",
                        label="Target Case Style"
                    )
                    case_convert_btn = gr.Button("🔁 Convert", size="lg", variant="primary")

                with gr.Column(scale=1):
                    converted_json_output = gr.Code(
                        language="json",
                        label="Converted JSON",
                        lines=10
                    )
                    case_convert_status = gr.Markdown()

            case_convert_btn.click(
                convert_case,
                inputs=[json_for_case, target_case],
                outputs=[converted_json_output, case_convert_status]
            )

        # ====== TAB 4: Merging ======
        with gr.TabItem("🔗 Merge JSON"):
            gr.Markdown("### 📦 Merge Multiple JSON Objects")

            with gr.Row():
                with gr.Column(scale=1):
                    json1 = gr.Code(
                        language="json",
                        label="JSON #1",
                        lines=8,
                        value='{"name": "John"}'
                    )
                    json2 = gr.Code(
                        language="json",
                        label="JSON #2",
                        lines=8,
                        value='{"age": 28}'
                    )
                    json3 = gr.Code(
                        language="json",
                        label="JSON #3 (optional)",
                        lines=8,
                        value='{"city": "New York"}'
                    )
                    merge_btn = gr.Button("➕ Merge", size="lg", variant="primary")

                with gr.Column(scale=1):
                    merged_output = gr.Code(
                        language="json",
                        label="Merged JSON",
                        lines=10
                    )
                    merge_status = gr.Markdown()

            merge_btn.click(
                merge_json_func,
                inputs=[json1, json2, json3],
                outputs=[merged_output, merge_status]
            )

        # TAB 5: Flattening =======
        with gr.TabItem("🔁 Flatten/Unflatten"):
            with gr.Tabs():
                with gr.TabItem("Flatten"):
                    gr.Markdown("### Flatten Nested JSON")

                    with gr.Row():
                        flatten_input = gr.Code(
                            language="json",
                            label="Nested JSON",
                            lines=10,
                            value='{"user": {"name": "John", "age": 28}}'
                        )
                        flatten_btn = gr.Button("Flatten", size="lg", variant="primary")

                        flatten_out = gr.Code(
                            language="json",
                            label="Flattened JSON",
                            lines=10
                        )
                    flatten_status = gr.Markdown()

                    flatten_btn.click(
                        flatten_json_func,
                        inputs=[flatten_input],
                        outputs=[flatten_out, flatten_status]
                    )

                with gr.TabItem("Unflatten"):
                    gr.Markdown("### Unflatten Flat JSON")

                    with gr.Row():
                        unflatten_input = gr.Code(
                            language="json",
                            label="Flat JSON",
                            lines=10,
                            value='{"user.name": "John", "user.age": 28}'
                        )
                        unflatten_btn = gr.Button("Unflatten", size="lg", variant="primary")

                        unflatten_out = gr.Code(
                            language="json",
                            label="Unflattened JSON",
                            lines=10
                        )
                    unflatten_status = gr.Markdown()

                    unflatten_btn.click(
                        unflatten_json_func,
                        inputs=[unflatten_input],
                        outputs=[unflatten_out, unflatten_status]
                    )

        # =================== TAB 6: History ============================
        with gr.TabItem("📜 History"):
            gr.Markdown("### Transformation History")

            with gr.Row():
                history_btn = gr.Button("📥 Download History", size="lg", variant="secondary")
                clear_history_btn = gr.Button("🗑️ Clear History", size="lg", variant="stop")

                history_output = gr.Textbox(
                    label="History Report",
                    lines=15
                )

            history_status = gr.Markdown()

            history_btn.click(
                download_history,
                outputs=[history_output]
            )

            clear_history_btn.click(
                clear_history,
                outputs=[history_output]
            )

        # =================== TAB 7: Guide ========================
        with gr.TabItem("Guide"):
            gr.Markdown("""
  #JSON Refiner - Complete Guide

## Input Format
Use simple **Key: Value** format:
```
name:John Doe
age:28
is_active:true
balance: 1500.50
```
## Type Inference
**Automatic type detection:**
- `true`, `false`, `yes`, `no` → Boolean
- `null`, `none`, `undefined` → Null
- `123`, `456` → Integer
- `3.14`, `2.5` → Float
- `[1, 2, 3]` → Array (if valid JSON)
- `{"key": "value"}` → Object (if valid JSON)
""")

print("\n ✅ JSON Refiner Advanced Ready!\n")
demo.launch(share=True, show_error=True, show_api=False)

import gradio as gr
import json
import re
import ast
from datetime import datetime
from pathlib import Path
from typing import Dict,List,Any,Tuple,Optional
import json5
from jsonschema import validate,ValidationError,Draft7Validator
from enum import Enum
# ==============================================================================================================================================
# JSON REFINER - ADVANCED VERSION WITH PREMIUM FEATURES (FIXED)
# ==============================================================================================================================================

class CaseStyle(Enum):
    """Case conversion styles"""
    SNAKE_CASE = "snake_case"
    CAMEL_CASE = "camel_case"
    KEBAB_CASE = "kebab-case"
    PASCAL_CASE = "pascal_case"

class JSONRefinerCore:
    """Advanced JSON parsing and refinement engine"""

    def __init__(self):
        self.conversion_log = []
        self.validation_errors = []
        self.transformation_history = []


    @staticmethod
    def to_snake_case(key: str) -> str:
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', key)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

    @staticmethod
    def to_camel_case(key: str) -> str:
        s = JSONRefinerCore.to_snake_case(key).split('_')
        return s[0] + ''.join(word.capitalize() for word in s[1:])

    @staticmethod
    def to_pascal_case(key: str) -> str:
        s = JSONRefinerCore.to_snake_case(key).split('_')
        return ''.join(word.capitalize() for word in s)

    @staticmethod
    def to_kebab_case(key: str) -> str:
        return JSONRefinerCore.to_snake_case(key).replace('_', '-')

    def normalize_key(self, key: str, target_case: CaseStyle) -> str:
        converted_key = key
        if target_case == CaseStyle.SNAKE_CASE:
            converted_key = JSONRefinerCore.to_snake_case(key)
        elif target_case == CaseStyle.CAMEL_CASE:
            converted_key = JSONRefinerCore.to_camel_case(key)
        elif target_case == CaseStyle.KEBAB_CASE:
            converted_key = JSONRefinerCore.to_kebab_case(key)
        elif target_case == CaseStyle.PASCAL_CASE:
            converted_key = JSONRefinerCore.to_pascal_case(key)

        if converted_key != key:
            self.conversion_log.append(f"Key '{key}' converted to '{converted_key}' ({target_case.value})")
        return converted_key

    @staticmethod
    def infer_type(value: str) -> Any:
        """Infer and convert value to correct JSON type"""
        value = value.strip()

        if value.lower() in ['null', 'none', 'nil', 'undefined', 'n/a', 'na']:
            return None

        if value.lower() in ['true', 'yes', 'on', '1']:
            return True
        if value.lower() in ['false', 'no', 'off', '0']:
            return False

        try:
            if '.' not in value:
                return int(value)
            else:
                return float(value)
        except ValueError:
            pass

        if (value.startswith('[') and value.endswith(']')) or \
           (value.startswith('{') and value.endswith('}')):
            try:
                return json5.loads(value)
            except ValueError:
                pass

        return value

    def refine_json(self, text_input: str, case_style: CaseStyle, remove_nulls: bool, flatten: bool) -> Tuple[str, List[str]]:
        """Refine JSON from key-value text"""
        self.conversion_log = []
        self.validation_errors = []
        parsed_data, errors = self.parse_key_value_text(text_input, case_style)

        if remove_nulls:
            parsed_data = self.remove_null_values(parsed_data)
            self.transformation_history.append((datetime.now(), "Removed null values"))

        if flatten:
            parsed_data = self.flatten_json(parsed_data)
            self.transformation_history.append((datetime.now(), "Flattened JSON"))

        output_json = json.dumps(parsed_data, indent=2, ensure_ascii=False)
        return output_json, self.conversion_log + errors

    @staticmethod
    def parse_key_value_text(text: str, case_style: CaseStyle = CaseStyle.SNAKE_CASE) -> Tuple[Dict, List[str]]:
        """Parse key-value text into dictionary"""
        result = {}
        errors = []
        duplicates = []

        lines = text.split('\n')

        for line_num, line in enumerate(lines, 1):
            line = line.strip()

            if not line or line.startswith('#'):
                continue

            if ':' not in line:
                errors.append(f"Line {line_num}: No colon separator found - '{line}'")
                continue

            try:
                key, value = line.split(':', 1)
                key = key.strip()

                if key in result:
                    duplicates.append(f"Line {line_num}: Duplicate key '{key}' found. Using latest value.")

                result[key] = JSONRefinerCore.infer_type(value)
            except Exception as e:
                errors.append(f"Line {line_num}: Error parsing '{line}' - {e}")
        return result, errors + duplicates

    @staticmethod
    def remove_null_values(obj: Any) -> Any:
        """Recursively remove null values from dicts and lists"""
        if isinstance(obj, dict):
            return {k: JSONRefinerCore.remove_null_values(v) for k, v in obj.items() if v is not None}
        elif isinstance(obj, list):
            return [JSONRefinerCore.remove_null_values(elem) for elem in obj if elem is not None]
        return obj

    @staticmethod
    def flatten_json(data: Dict, parent_key: str = '', sep: str = '.') -> Dict:
        """Flatten a nested JSON dictionary"""
        items = []
        for k, v in data.items():
            new_key = parent_key + sep + k if parent_key else k
            if isinstance(v, dict):
                items.extend(JSONRefinerCore.flatten_json(v, new_key, sep=sep).items())
            else:
                items.append((new_key, v))
        return dict(items)

    @staticmethod
    def unflatten_json(data: Dict, sep: str = '.') -> Dict:
        """Unflatten a flattened JSON dictionary"""
        result = {}
        for key, value in data.items():
            parts = key.split(sep)
            d = result
            for part in parts[:-1]:
                if part not in d:
                    d[part] = {}
                d = d[part]
            d[parts[-1]] = value
        return result

    @staticmethod
    def validate_json_schema(data: Dict, schema: Dict) -> Tuple[bool, List[str]]:
        """Validate JSON against schema"""
        errors = []
        try:
            validate(instance=data, schema=schema)
            return True, []
        except ValidationError as e:
            return False, [str(e)]
        except Exception as e:
            return False, [f"Schema validation error: {str(e)}"]

    @staticmethod
    def check_required_fields(data: Dict, required_fields: List[str]) -> Tuple[bool, List[str]]:
        """Check for required fields"""
        errors = []
        missing = []
        for field in required_fields:
            if field not in data:
                missing.append(field)

        if missing:
            return False, [f"Missing required fields: {', '.join(missing)}"]
        return True, []

    def merge_json_objects(self, json_strings: List[str]) -> Tuple[str, str]:
        """Merge multiple JSON strings into one"""
        merged_data = {}
        errors = []
        for i, json_str in enumerate(json_strings):
            if not json_str.strip():
                continue
            try:
                data = json.loads(json_str)
                if not isinstance(data, dict):
                    errors.append(f"Input {i+1} is not a JSON object and cannot be merged.")
                    continue
                merged_data.update(data)
            except json.JSONDecodeError as e:
                errors.append(f"Error parsing JSON input {i+1}: {e}")

        if errors:
            return "", "❌ " + "; ".join(errors)
        else:
            self.transformation_history.append((datetime.now(), f"Merged {len(json_strings)} JSON objects"))
            return json.dumps(merged_data, indent=2, ensure_ascii=False), "✅ JSON objects merged!"

    def get_history(self) -> str:
        """Return the transformation history"""
        if not self.transformation_history:
            return "No transformations performed yet."
        report = "Transformation History:\n"
        for timestamp, action in self.transformation_history:
            report += f"- {timestamp.strftime('%Y-%m-%d %H:%M:%S')} : {action}\n"
        return report

    def clear_history(self):
        """Clear the transformation history"""
        self.transformation_history = []

refiner = JSONRefinerCore()

def process_json(text_input, case_style_str, remove_nulls, flatten, pretty_print):
    case_style = CaseStyle[case_style_str.upper().replace("-", "_")]
    refined_json, logs = refiner.refine_json(text_input, case_style, remove_nulls, flatten)
    status_message = "\n".join([f"* {log}" for log in logs]) if logs else "✅ JSON processed successfully!"
    return refined_json, status_message

def validate_json(json_text, schema_text, required_fields_str):
    errors = []
    try:
        data = json.loads(json_text)
    except json.JSONDecodeError as e:
        return False, [f"Invalid JSON: {e}"]

    is_valid_schema, schema_errors = True, []
    if schema_text.strip():
        try:
            schema = json.loads(schema_text)
            is_valid_schema, schema_errors = refiner.validate_json_schema(data, schema)
        except json.JSONDecodeError as e:
            schema_errors.append(f"Invalid Schema JSON: {e}")

    required_fields = [f.strip() for f in required_fields_str.split(',') if f.strip()]
    is_valid_fields, field_errors = refiner.check_required_fields(data, required_fields)

    all_errors = schema_errors + field_errors
    if not is_valid_schema or not is_valid_fields:
        return "❌ Validation Failed", "\n".join(all_errors) if all_errors else "Unknown validation error."
    return "✅ Validation Successful!", "No validation errors."

def convert_case(json_text: str, target_case: str) -> Tuple[str, str]:
    """Convert JSON keys to different case styles"""
    try:
        data = json.loads(json_text)
        case_enum = CaseStyle[target_case.upper().replace("-", "_")]

        def convert_keys(obj):
            if isinstance(obj, dict):
                return {
                    refiner.normalize_key(k, case_enum): convert_keys(v)
                    for k, v in obj.items()
                }
            elif isinstance(obj, list):
                return [convert_keys(item) for item in obj]
            return obj

        converted = convert_keys(data)
        output = json.dumps(converted, indent=2, ensure_ascii=False)
        refiner.transformation_history.append((datetime.now(), f"Converted to {target_case} case"))
        return output, f"✅ Converted to {target_case}!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def merge_json_func(json1_str, json2_str, json3_str):
    json_list = [json1_str, json2_str, json3_str]
    merged_json, status = refiner.merge_json_objects(json_list)
    return merged_json, status

def flatten_json_func(json_text: str) -> Tuple[str, str]:
    """Flatten JSON structure"""
    try:
        data = json.loads(json_text)
        flattened = refiner.flatten_json(data)
        output = json.dumps(flattened, indent=2, ensure_ascii=False)
        refiner.transformation_history.append((datetime.now(), "Flattened JSON"))
        return output, "✅ JSON flattened!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def unflatten_json_func(json_text: str) -> Tuple[str, str]:
    """Unflatten JSON structure"""
    try:
        data = json.loads(json_text)
        unflattened = refiner.unflatten_json(data)
        output = json.dumps(unflattened, indent=2, ensure_ascii=False)
        refiner.transformation_history.append((datetime.now(), "Unflattened JSON"))
        return output, "✅ JSON unflattened!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def download_history():
    return refiner.get_history()

def clear_history():
    refiner.clear_history()
    return "History cleared."


with gr.Blocks(title="JSON Refiner") as demo:
    gr.Markdown("# 🗄️ JSON Refiner - Advanced Edition")

    with gr.Tabs():
        # ================== TAB 1 : Core Refining ========================
        with gr.TabItem("Core Refining"):
            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("### 📄 Input Format")
                    text_input = gr.Textbox(
                        label="Key-Value Text",
                        lines=12,
                        value="name: John Doe\nage: 28\nis_active: true\nbalance: 1500.50\nemail: john@example.com\ntags: [\"admin\", \"user\"]"
                    )
                    case_style = gr.Radio(
                        ["snake_case", "camel_case", "kebab-case", "pascal_case"],
                        value="snake_case",
                        label="Key Case Style 😊"
                    )

                with gr.Column(scale=2):
                    gr.Markdown("### 🛠️ Refined JSON Output")
                    json_output = gr.Code(
                        language="json",
                        label="Output JSON",
                        lines=15,
                    )
                    status_output = gr.Markdown()

            with gr.Row():
                remove_nulls = gr.Checkbox(label="Remove Nulls", value=False)
                flatten = gr.Checkbox(label="Flatten", value=False)
                pretty_print = gr.Checkbox(label="Pretty Print", value=True)
                refine_btn = gr.Button("✨ Refine JSON", size="lg", variant="primary")

            refine_btn.click(
                process_json,
                inputs=[text_input, case_style, remove_nulls, flatten, pretty_print],
                outputs=[json_output, status_output]
            )

        # ============== TAB 2: Validation ==============
        with gr.TabItem("☑️ Validation"):
            gr.Markdown("### 🔍 Validate JSON Structure")

            with gr.Row():
                with gr.Column(scale=1):
                    json_to_validate = gr.Code(
                        language="json",
                        label="JSON to Validate",
                        lines=10,
                        value='{"name": "John", "age": 28,"email":"john@example.com"}'
                    )
                    required_fields_input = gr.Textbox(
                        label="Required Fields (comma-separated)",
                        value="name, age, email"
                    )
                    validate_btn = gr.Button("✅ Validate", size="lg", variant="primary")

                with gr.Column(scale=1):
                    schema_input = gr.Code(
                        language="json",
                        label="JSON Schema (optional)",
                        lines=10,
                        value='{"type": "object", "properties": {"name": {"type": "string"}, "age": {"type": "integer"}}, "required": ["name"]}'
                    )
                    validation_status = gr.Markdown()
                    validation_errors_output = gr.Textbox(label="Validation Details", lines=5)

            validate_btn.click(
                validate_json,
                inputs=[json_to_validate, schema_input, required_fields_input],
                outputs=[validation_status, validation_errors_output]
            )

        # ==== TAB 3: Case Conversion ============
        with gr.TabItem("🐼 Case Conversion"):
            gr.Markdown("### 🐙 Convert JSON Key Cases")

            with gr.Row():
                with gr.Column(scale=1):
                    json_for_case = gr.Code(
                        language="json",
                        label="Input JSON",
                        lines=10,
                        value='{"firstName": "John", "lastName": "Doe"}'
                    )

                    target_case = gr.Radio(
                        ["snake_case", "camel_case", "kebab-case", "pascal_case"],
                        value="camelCase",
                        label="Target Case Style"
                    )
                    case_convert_btn = gr.Button("🔁 Convert", size="lg", variant="primary")

                with gr.Column(scale=1):
                    converted_json_output = gr.Code(
                        language="json",
                        label="Converted JSON",
                        lines=10
                    )
                    case_convert_status = gr.Markdown()

            case_convert_btn.click(
                convert_case,
                inputs=[json_for_case, target_case],
                outputs=[converted_json_output, case_convert_status]
            )

        # ====== TAB 4: Merging ======
        with gr.TabItem("🔗 Merge JSON"):
            gr.Markdown("### 📦 Merge Multiple JSON Objects")

            with gr.Row():
                with gr.Column(scale=1):
                    json1 = gr.Code(
                        language="json",
                        label="JSON #1",
                        lines=8,
                        value='{"name": "John"}'
                    )
                    json2 = gr.Code(
                        language="json",
                        label="JSON #2",
                        lines=8,
                        value='{"age": 28}'
                    )
                    json3 = gr.Code(
                        language="json",
                        label="JSON #3 (optional)",
                        lines=8,
                        value='{"city": "New York"}'
                    )
                    merge_btn = gr.Button("➕ Merge", size="lg", variant="primary")

                with gr.Column(scale=1):
                    merged_output = gr.Code(
                        language="json",
                        label="Merged JSON",
                        lines=10
                    )
                    merge_status = gr.Markdown()

            merge_btn.click(
                merge_json_func,
                inputs=[json1, json2, json3],
                outputs=[merged_output, merge_status]
            )

        # TAB 5: Flattening =====
        with gr.TabItem("🔁 Flatten/Unflatten"):
            with gr.Tabs():
                with gr.TabItem("Flatten"):
                    gr.Markdown("### Flatten Nested JSON")

                    with gr.Row():
                        flatten_input = gr.Code(
                            language="json",
                            label="Nested JSON",
                            lines=10,
                            value='{"user": {"name": "Jeni", "age": 20}}'
                        )
                        flatten_btn = gr.Button("Flatten", size="lg", variant="primary")

                        flatten_out = gr.Code(
                            language="json",
                            label="Flattened JSON",
                            lines=10
                        )
                    flatten_status = gr.Markdown()

                    flatten_btn.click(
                        flatten_json_func,
                        inputs=[flatten_input],
                        outputs=[flatten_out, flatten_status]
                    )

                with gr.TabItem("Unflatten"):
                    gr.Markdown("### Unflatten Flat JSON")

                    with gr.Row():
                        unflatten_input = gr.Code(
                            language="json",
                            label="Flat JSON",
                            lines=10,
                            value='{"user.name": "Jeni", "user.age": 20}'
                        )
                        unflatten_btn = gr.Button("Unflatten", size="lg", variant="primary")

                        unflatten_out = gr.Code(
                            language="json",
                            label="Unflattened JSON",
                            lines=10
                        )
                    unflatten_status = gr.Markdown()

                    unflatten_btn.click(
                        unflatten_json_func,
                        inputs=[unflatten_input],
                        outputs=[unflatten_out, unflatten_status]
                    )

        # =================== TAB 6: History ============================
        with gr.TabItem("📜 History"):
            gr.Markdown("### Transformation History")

            with gr.Row():
                history_btn = gr.Button("📥 Download History", size="lg", variant="secondary")
                clear_history_btn = gr.Button("🗑️ Clear History", size="lg", variant="stop")

                history_output = gr.Textbox(
                    label="History Report",
                    lines=15
                )

            history_status = gr.Markdown()

            history_btn.click(
                download_history,
                outputs=[history_output]
            )

            clear_history_btn.click(
                clear_history,
                outputs=[history_output]
            )

        # =================== TAB 7: Guide ========================
        with gr.TabItem("Guide"):
            gr.Markdown("""
  #JSON Refiner - Complete Guide

## Input Format
Use simple **Key: Value** format:
```
name:John Doe
age:28
is_active:true
balance: 1500.50
```
## Type Inference
**Automatic type detection:**
- `true`, `false`, `yes`, `no` → Boolean
- `null`, `none`, `undefined` → Null
- `123`, `456` → Integer
- `3.14`, `2.5` → Float
- `[1, 2, 3]` → Array (if valid JSON)
- `{"key": "value"}` → Object (if valid JSON)
""")

print("\n ✅ JSON Refiner Advanced Ready!\n")
demo.launch(share=True, show_error=True, show_api=False)